export type TEvent = {
  onTeleport?: boolean;
  onNextTeleport?: boolean;
  onPrevTeleport?: boolean;
  onStartFarmEchoes?: boolean;
  onStopFarmEchoes?: boolean;
  onSaveConfig?: boolean;
  onLoadConfig?: boolean;
  onApplyBuff?: boolean;
  onRefreshEchoes?: boolean;
  isEchoesRefreshed?: boolean;
  onEnterDungeon?: boolean;
  onWeaponAdded?: boolean;
  onRoleReplaced?: boolean;
  onChangeUID?: boolean;
  onShowFPS?: boolean;
  onESPTrigger?: boolean;
  onTreasureTpOverlayTrigger?: boolean;
  onUnlockFPS?: boolean;
  onFOVChanged?: boolean;
};
