// tiap event -> array (queue)
export const EventState = {
  onTeleport: { status: false, data: null },
  onNextTeleport: { status: false, data: null },
  onPrevTeleport: { status: false, data: null },
  onStartFarmEchoes: { status: false, data: null },
  onStopFarmEchoes: { status: false, data: null },
  onRefreshEchoes: { status: false, data: null },
  isEchoesRefreshed: { status: false, data: null },
  onWeaponAdded: { status: false, data: null },
  onRoleReplaced: { status: false, data: null },
  onApplyBuff: { status: false, data: null },
  onEnterDungeon: { status: false, data: null },
  onChangeUID: { status: false, data: null },
  onSaveConfig: { status: false, data: null },
  onLoadConfig: { status: false, data: null },
  onFOVChanged: { status: false, data: null },
  onESPTrigger: { status: false, data: null },
  onShowFPS: { status: false, data: null },
  onTreasureTpOverlayTrigger: { status: false, data: null },
  onUnlockFPS: { status: false, data: null },
};

// daftar event yang auto-reset
export const oneTimeEvents: (keyof typeof EventState)[] = [
  "onTeleport",
  "onNextTeleport",
  "onPrevTeleport",
  "onStopFarmEchoes",
  "onApplyBuff",
  "onSaveConfig",
  "onLoadConfig",
  "onEnterDungeon",
  "onWeaponAdded",
  "onRoleReplaced",
  "onChangeUID",
  "onShowFPS",
  "onESPTrigger",
  "onTreasureTpOverlayTrigger",
  "onUnlockFPS",
  "onFOVChanged",
];
