export const DEFAULT_KEYBINDS = {
  ModMenu: { key: null, type: "Toggle", action: "ModMenu" },
  TreasureTeleport: { key: null, type: "Toggle", action: "TreasureTeleport" },
  KillAura: { key: null, type: "Toggle", action: "KillAura" },
  Flight: { key: null, type: "Toggle", action: "Flight" },
  MobVacuum: { key: null, type: "Toggle", action: "MobVacuum" },
  WorldSpeed: { key: null, type: "Toggle", action: "WorldSpeed" },
  PlayerSpeed: { key: null, type: "Toggle", action: "PlayerSpeed" },
  NextTp: { key: null, type: "Toggle", action: "NextTp" },
  NoClip: { key: null, type: "Toggle", action: "NoClip" },
  PrevTp: { key: null, type: "Toggle", action: "PrevTp" },
  MarkTp: { key: null, type: "Toggle", action: "MarkTp" },
  QuestTp: { key: null, type: "Toggle", action: "QuestTp" },
  ReloadBuffConfig: { key: null, type: "Toggle", action: "ReloadBuffConfig" },
  AlwaysShowCursor: { key: null, type: "Toggle", action: "AlwaysShowCursor" },
  FreezeGameTime: { key: null, type: "Toggle", action: "FreezeGameTime" },
  EchoVacuum: { key: null, type: "Toggle", action: "EchoVacuum" },
  AutoRestartDungeon: { key: null, type: "Toggle", action: "AutoRestartDungeon" },
  CopyTpCordinate: { key: null, type: "Toggle", action: "CopyTpCordinate" },
  UnstuckLoading: { key: null, type: "Toggle", action: "UnstuckLoading" },
  ApplyBuff: { key: null, type: "Toggle", action: "ApplyBuff" },
  SkipQuestNode: { key: null, type: "Toggle", action: "SkipQuestNode" },
  StatEnhancement: { key: null, type: "Toggle", action: "StatEnhancement" },
};
export type KEY_TYPE = typeof DEFAULT_KEYBINDS;
